server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: music-service
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/music/**
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtRjOFzTbeqfVp528GcBI
      vuUz2tF8tfy/bT8xaWSKuY3KK46lPtsbH+cqQNo/2BIRt4vqus2nr2Y8mMU1VC9h
      ZXz/Nz3uzunNgGBExIlKJrqiDRuQya522coNFXfPGzDQpcPsLonkzkwqvUEZh22/
      v5cHsHs7vGtIG/hdmhB28ab77a0Z3NUcrRuB9QVxPiwVlhOOdSkT0v8eVQzr+IE1
      UGU+8spLkoScSYihzo6uDI1dvtvJ6DygxNkb1Z8Lx9C3zZ9FM5YJahaWzdmhHYFj
      P+UnKakPUsajFrUeisvqy5X7E27t1G+6SX62IOWe6/vInEfB0H0vUM4Xvu1WfoM2
      8QIDAQAB
      -----END PUBLIC KEY-----
